name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 1.3.4+4
homepage: https://github.com/fluttercommunity/chewie

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=1.22.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  provider: '>=5.0.0 <7.0.0'
  video_player: ^2.4.4
  wakelock: ^0.6.1+2
  youtube_explode_dart:
    git:
        url: git@github.com:qoohoo-app/youtube_explode_dart.git
        ref: "0ff2ecc5989f55fe164b75e51dae49013e18c0c9"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
